-- 2022년 1월의 도서 판매 :: 저자, 카테고리 별 매출액을 구함 (판매량 * 판매가)
-- 저자ID, 저자명, 카테고리, 매출액 리스트 출력
-- 저자ID 오름차순, 카테고리 내림차순

# SELECT C.AUTHOR_ID, C.AUTHOR_NAME, C.CATEGORY, SUM (D.SALES * C.PRICE) AS TOTAL_SALES
# FROM 
#     (SELECT A.AUTHOR_ID, A.BOOK_ID, A.CATEGORY,A.PRICE,B.AUTHOR_NAME
#      FROM BOOK A JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
#     GROUP BY A.CATEGORY, B.AUTHOR_NAME ) C
    
#     JOIN BOOK_SALES D
#     ON D.BOOK_ID = C.BOOK_ID
#     WHERE MONTH(D.SALES_DATE) = 1
    
# GROUP BY C.AUTHOR_ID,C.CATEGORY
# ORDER BY C.AUTHOR_ID, C.CATEGORY DESC
    


SELECT C.AUTHOR_ID, C.AUTHOR_NAME, C.CATEGORY, sum(D.SALES * C.PRICE) AS TOTAL_SALES
FROM 
    (SELECT A.AUTHOR_ID, A.BOOK_ID, A.CATEGORY,A.PRICE,B.AUTHOR_NAME
     FROM BOOK A JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
    GROUP BY A.book_id, A.category ) C
    
    JOIN BOOK_SALES D
    ON D.BOOK_ID = C.BOOK_ID
    WHERE MONTH(D.SALES_DATE) = 1
    
GROUP BY C.AUTHOR_ID, C.AUTHOR_NAME, C.CATEGORY
ORDER BY C.AUTHOR_ID, C.CATEGORY DESC
    