-- 중성화 안됐지만  -> 중성화됨
-- 아이디, 생물 종, 이름
-- 아이디 순으로 조회

SELECT A.ANIMAL_ID , A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A 
    JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE 'Intact%'
 and (B.SEX_UPON_OUTCOME LIKE 'Spayed%' or B.SEX_UPON_OUTCOME LIKE 'Neutered%')
 ORDER BY A.ANIMAL_ID
 