--  3월 생일인 여성
-- 전화번호 null경우 제외
-- 회원Id 기준 오름차순


SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d')  
as DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL AND DATE_OF_BIRTH LIKE '%-03-%' and GENDER LIKE 'W'
ORDER BY MEMBER_ID